version: "3.9"

services:
  mysql_db:
    image: mariadb:latest
    container_name: mymariadbserver
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  mongo_db:
    image: mongo:latest
    container_name: mymongodbserver
    ports:
      - 27017:27017

