version: '3.8'

services:
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE_URL: ${MYSQL_DATABASE_URL}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}      
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql