name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Docker Images
        run: |
          docker build -t carlosgibe/node:dev ./server
          docker build -t carlosgibe/mariadb:dev ./server
          docker build -t carlosgibe/mongo:dev ./server

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          password-stdin: true

      - name: Push Docker Images to DockerHub
        run: |
          docker push carlosgibe/node:dev
          docker push carlosgibe/mariadb:dev
          docker push carlosgibe/mongo:dev
