name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Docker Images
        run: |
          docker build -t carlosgibe/node:dev ./ruta-de-tu-app
          docker build -t carlosgibe/mariadb:dev ./ruta-de-tu-mysql-db
          docker build -t carlosgibe/mongo:dev ./ruta-de-tu-mongo-db

      - name: Log in to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Images to DockerHub
        run: |
          docker push carlosgibe/node:dev
          docker push carlosgibe/mariadb:dev
          docker push carlosgibe/mongo:dev
